name: walk_smarter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1
environment:
  sdk: ^3.1.1

dependencies:
  pocketbase: ^0.18.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+11
  english_words: ^4.0.0
  provider: ^6.0.4
  intl: ^0.17.0  # Added the intl package here
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/WalkSmarterAppIcon.png'
