name: walk_smarter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1
environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.11.0
  image_picker: ^0.8.4+11
  english_words: ^4.0.0
  provider: ^6.0.0
  intl: ^0.17.0
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  google_maps_flutter: ^2.0.6
  google_maps_webservice: ^0.0.19+1
  geolocator: ^9.0.2
  geocoding: ^3.0.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    # - .env
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/WalkSmarterAppIcon.png'
